load("@rules_python//python:defs.bzl", "py_test")

test_suite(
    name = "test",
    tests = [
        "//bindings/python3/ewcore_tests/math:test",
    ],
    visibility = ["//visibility:public"],
)

