filegroup(
    name = "bindings",
    srcs = ["//bindings/python3"],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "test",
    tests = [
        "//bindings/python3/ewcore_tests:test",
    ],
    visibility = ["//visibility:public"],
)
